name: educare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  table_calendar: ^3.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.3.0 
  supabase_flutter: ^2.0.0
  flutter_local_notifications: ^17.1.2
  mask_text_input_formatter: ^2.5.0
  flutter_reactive_ble: ^5.0.2
  permission_handler: ^12.0.1
  app_links: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

  assets:
   - assets/images/logo.png
   - assets/images/emoji.png
   - assets/images/diario.png
   - assets/images/atividades.webp
   - assets/fonts/

dependency_overrides:
  intl: 0.20.2 

  